config/urls.py
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.urls.base import reverse_lazy



urlpatterns = [
    path("", lambda x: HttpResponseRedirect(reverse_lazy("posts:list"))),
    path("admin/", admin.site.urls),
    path("posts/", include("core.urls")),
    # path("users/", include("users.urls")),
]

core/urls.py
from django.urls import path
from .views import PostView, PostDetailView, PostDeleteView, PostCreateView, PostUpdateView


app_name = "posts"

urlpatterns = [
    path("", PostView.as_view(), name="list"),
    path("<int:post_id>/", PostDetailView.as_view(), name="detail"),
    path("<int:post_id>/delete", PostDeleteView.as_view(), name="delete"),
    path("post_update/<int:post_id>/", PostUpdateView.as_view(), name="update"),
    path("post_create/", PostCreateView.as_view(), name="create")
]

users/urls.py
from django.urls import path
from .views import users

app_name = "users"

urlpatterns = [
    path("", users),
]

core/models.py
from django.db import models
from config import settings


class TimestampMixin(models.Model):

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimestampMixin):
    title = models.CharField(
        max_length=100, null=False, blank=False
    )  # blank=False - нельзя оставлять пустым
    content = models.TextField(null=False, blank=False)
    image = models.CharField(
        max_length=255, null=True, blank=True
    )  # blank=True - можно оставлять пустым
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=False, on_delete=models.SET_NULL
    )

    def __str__(self) -> str:
        return f"{self.title}"


class Likes(TimestampMixin):
    post = models.ForeignKey("Post", null=False, blank=False, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=False, blank=False, on_delete=models.CASCADE
    )
    status = models.BooleanField(null=True, blank=True)

users/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

config/views.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("django.contrib.auth.urls")),
    path("", include("core.urls")),
    path("", include("users.urls")),
]

core/views.py
from django.urls import reverse_lazy
from .models import Post
from .forms import PostForm
from django.contrib.auth import get_user_model
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView


User = get_user_model()

class PostView(ListView):
    template_name = "core/posts.html"
    queryset = Post.objects.all()
    # context_object_name = "posts"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        posts = Post.objects.all()
        results = [
            (
                p,
                p.likes_set.filter(status=True).count(),
                p.likes_set.filter(status=False).count(),
            )
            for p in posts
        ]

        ctx["results"] = results

        return ctx


class PostDetailView(DetailView):
    queryset = Post.objects.all()
    template_name = "core/post.html"
    pk_url_kwarg = "post_id"

class PostDeleteView(DeleteView):
    queryset = Post.objects.all()
    template_name = 'core/post_delete.html'
    pk_url_kwarg = 'post_id'
    success_url = reverse_lazy("posts:list")

class PostUpdateView(UpdateView):
    queryset = Post.objects.all()
    template_name = 'core/post_update.html'
    pk_url_kwarg = 'post_id'
    fields = ['title', 'content']
    success_url = reverse_lazy("posts:list")

class PostCreateView(CreateView):
    queryset = Post.objects.all()
    template_name = 'core/post_create.html'
    form_class = PostForm
    success_url = reverse_lazy("posts:list")

    def form_valid(self, form):
        user = User.objects.first()
        form.instance.user = user
        return super().form_valid(form)

users/views.py
from django.http import HttpResponse
from django.contrib.auth import get_user_model

User = get_user_model()


def users(request):
    users = User.objects.all()
    results = ", ".join([user.username for user in users])
    return HttpResponse(results)

templates/base.html
<html>
    <head>
        <title>My First Social Network</title>
    </head>
    <body>
        <header>
            <h1><font color="green">My First Social Network</font></h1>
        </header>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html> 

templates/core/post.html
{% extends 'base.html' %}

{% block content %}

    <a href="/posts">&#8592 Back</a>

    <h3> {{ object }} </h3> 
    <p> {{ object.content }} </p>
    <p> ------------ </p>
    <p> Автор поста: <i> {{ object.user.first_name }} {{ object.user.last_name }} </i></p>
    <p> Пост создан: <i> {{ object.created_at }} </p></i>
    <p> ------------ </p>

    <a href="{% url 'posts:update' object.id %}">Update Post</a>
    <p></p>
    <a href="{% url 'posts:delete' object.id %}">Delete post</a>

{% endblock content %}

templates/core/post_create.html
{% extends 'base.html' %}

{% block content %}
    <h2>Post Creation</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Confirm</button>
    </form>
{% endblock content %}

templates/core/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ object }}</h3>
    <p>{{ post.content }}</p>
    <form action="" method="post">{% csrf_token %}
    <input type="submit" value="Delete Post">
    </form>
{% endblock content %} 

templates/core/post_update.html
{% extends 'base.html' %}

{% block content %}
    <h3>{{ object }}</h3>
    <p>{{ post.content }}</p>
    <form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Post">
    </form>
{% endblock content %}

templates/core/posts.html
{% extends 'base.html' %}

{% block content %}

    <h2><a href="{% url 'posts:create' %}">Create Post</a></h2>

    <h1>Posts:</h1>

    {% for post, likes, dislikes in results %}
    <p>[#{{ post.id }}]  <b><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></b></p>
    <p><i>&#129304;({{ likes }}), &#128078;({{ dislikes }})</i></p>
    <p>author:  {{ post.user.first_name }} {{ post.user.last_name }}</p>
    <p>-------</p>
    {% endfor %}

{% endblock content %}